### ISSUE TITLE
Selectivity plot for multiple gears and maturity not working

### ISSUE THREAD

**Issue by Shawkshaw** [cgrandin/iscam-gui#1]
In the iscam-gui.r line 317 we want to implement plotselex with option 3 as the second variable in the function but when we do this nothing is plotted.  With option 2 we get all gears plotted including the surveys (gears 4/5) which we do not want to plot.  Option 1 plots only 1 selectivity but we are not clear on which gear it is?  

Note: We are talking about the selectivity in the ScenarioFigs tab of the gui

**Comment by cgrandin** [comment]
This should be solved in commits 882d809 and 9b3923b9dff00099773e65ba423fda253456b377. There are now two plotNum choices, 1=single selectivity line (gear 1) and 2=all gears. There is also an argument called plot.fixed which can be set to FALSE so that the surveys (fixed selectivity) are not plotted. Also there is an argument which is used to differentiate between using the 'bio' object for maturity (created using the Biotool tab) or the maturity vector in the data file.

These have been rigged to several new buttons in the 'ScenarioFigs' tab in the Selectivity section.

Note that the gears are numbered as they are numbered in the input files.
